### ISSUE TITLE
The data command returns json with single-quotes, which is invalid

### ISSUE THREAD

**Issue by felciano** [JoeBashe/stl-scraper#11]
The `stl.py data` command returns information about a listing in json form, where the keys and most values are delimited in single-quotes. This resulting json file seems to break most parsers and beautifiers, and I believe it is because the json standard mandates double quotes (e.g. see https://www.w3schools.com/js/js_json_syntax.asp). Would it be possible to switch to double-quotes as the standard?

**Comment by JoeBashe** [comment]
Hi @felciano, thank you for submitting the issue! You're absolutely correct, JSON needs to be double quoted. What you're seeing is simply the default string output of a python dict, which is why it is single quoted. 

I have updated the program to output valid JSON now, which I think is a great improvement! Thank you for the input. 🙏
